In [1]:
import pandas as pd

df = pd.read_csv(r"../data/raw/apartments_pl_2023_08.csv")

df

,id,city,type,squareMeters,rooms,floor,floorCount,buildYear,latitude,longitude,...,pharmacyDistance,ownership,buildingMaterial,condition,hasParkingSpace,hasBalcony,hasElevator,hasSecurity,hasStorageRoom,price
0,f8524536d4b09a0c8ccc0197ec9d7bde,szczecin,blockOfFlats,63.00,3.0,4.0,10.0,1980.0,53.378933,14.625296,...,0.413,condominium,concreteSlab,NaN,yes,yes,yes,no,yes,415000
1,accbe77d4b360fea9735f138a50608dd,szczecin,blockOfFlats,36.00,2.0,8.0,10.0,NaN,53.442692,14.559690,...,0.205,cooperative,concreteSlab,NaN,no,yes,yes,no,yes,395995
2,8373aa373dbc3fe7ca3b7434166b8766,szczecin,tenement,73.02,3.0,2.0,3.0,NaN,53.452222,14.553333,...,0.280,condominium,brick,NaN,no,no,no,no,no,565000
3,0a68cd14c44ec5140143ece75d739535,szczecin,tenement,87.60,3.0,2.0,3.0,NaN,53.435100,14.532900,...,0.087,condominium,brick,NaN,yes,yes,no,no,yes,640000
4,f66320e153c2441edc0fe293b54c8aeb,szczecin,blockOfFlats,66.00,3.0,1.0,3.0,NaN,53.410278,14.503611,...,0.514,condominium,NaN,NaN,no,no,no,no,no,759000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18900,ae88d7ea0a7a5fa0e9d287cfd78e5676,bydgoszcz,blockOfFlats,84.00,3.0,NaN,4.0,2000.0,53.112927,17.975630,...,0.164,cooperative,brick,NaN,yes,yes,no,no,yes,789000
18901,6a4b30b5fcdee00bfe5bcc0da82df9b1,bydgoszcz,blockOfFlats,94.30,4.0,NaN,2.0,1998.0,53.115921,17.956396,...,0.428,condominium,NaN,NaN,no,yes,no,no,yes,699000
18902,1e7f4f1fdfea31eb84e071d697839632,bydgoszcz,NaN,50.12,2.0,1.0,1.0,NaN,53.126000,18.007900,...,0.205,condominium,brick,NaN,yes,no,no,no,no,360000
18903,d971c4ed3aab9919bf203e96019a678e,bydgoszcz,tenement,100.00,4.0,3.0,4.0,1910.0,53.126000,18.007900,...,0.205,condominium,brick,premium,yes,yes,no,no,yes,590000
18904,cd0241b70b79aaaf767a0dd3a7cfbb31,bydgoszcz,NaN,81.07,5.0,1.0,4.0,2019.0,53.115921,17.956396,...,0.428,condominium,NaN,NaN,no,yes,yes,no,no,699000

In [2]:
nulos = df.isnull().sum().sort_values(ascending=False)
print(nulos)

condition               14344
buildingMaterial         7387
type                     4039
floor                    3438
buildYear                3271
hasElevator               926
collegeDistance           565
floorCount                262
clinicDistance             88
restaurantDistance         58
pharmacyDistance           27
postOfficeDistance         25
schoolDistance             14
kindergartenDistance       13
longitude                   0
latitude                    0
rooms                       0
id                          0
city                        0
squareMeters                0
poiCount                    0
centreDistance              0
ownership                   0
hasParkingSpace             0
hasBalcony                  0
hasSecurity                 0
hasStorageRoom              0
price                       0
dtype: int64

In [3]:
size = df.shape
print(size)

(18905, 28)

In [4]:
duplas = df.duplicated().sum()
print(duplas)

0

In [5]:
colunas = df.columns
print(colunas)

Index(['id', 'city', 'type', 'squareMeters', 'rooms', 'floor', 'floorCount',
       'buildYear', 'latitude', 'longitude', 'centreDistance', 'poiCount',
       'schoolDistance', 'clinicDistance', 'postOfficeDistance',
       'kindergartenDistance', 'restaurantDistance', 'collegeDistance',
       'pharmacyDistance', 'ownership', 'buildingMaterial', 'condition',
       'hasParkingSpace', 'hasBalcony', 'hasElevator', 'hasSecurity',
       'hasStorageRoom', 'price'],
      dtype='str')

In [6]:
tipo = df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18905 entries, 0 to 18904
Data columns (total 28 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    18905 non-null  str
 1   city                  18905 non-null  str
 2   type                  14866 non-null  str
 3   squareMeters          18905 non-null  float64
 4   rooms                 18905 non-null  float64
 5   floor                 15467 non-null  float64
 6   floorCount            18643 non-null  float64
 7   buildYear             15634 non-null  float64
 8   latitude              18905 non-null  float64
 9   longitude             18905 non-null  float64
 10  centreDistance        18905 non-null  float64
 11  poiCount              18905 non-null  float64
 12  schoolDistance        18891 non-null  float64
 13  clinicDistance        18817 non-null  float64
 14  postOfficeDistance    18880 non-null  float64
 15  kindergartenDistance  18892 non-null  float64
 16  restaurantDistance    18847 non-null  float64
 17  collegeDistance       18340 non-null  float64
 18  pharmacyDistance      18878 non-null  float64
 19  ownership             18905 non-null  str
 20  buildingMaterial      11518 non-null  str
 21  condition             4561 non-null   str
 22  hasParkingSpace       18905 non-null  str
 23  hasBalcony            18905 non-null  str
 24  hasElevator           17979 non-null  str
 25  hasSecurity           18905 non-null  str
 26  hasStorageRoom        18905 non-null  str
 27  price                 18905 non-null  int64
dtypes: float64(16), int64(1), str(11)
memory usage: 4.0 MB

In [7]:
df.describe()

,squareMeters,rooms,floor,floorCount,buildYear,latitude,longitude,centreDistance,poiCount,schoolDistance,clinicDistance,postOfficeDistance,kindergartenDistance,restaurantDistance,collegeDistance,pharmacyDistance,price
count,18905.000000,18905.000000,15467.000000,18643.000000,15634.000000,18905.000000,18905.000000,18905.000000,18905.000000,18891.000000,18817.000000,18880.000000,18892.000000,18847.000000,18340.000000,18878.000000,1.890500e+04
mean,58.509976,2.676752,3.339820,5.279783,1984.551043,52.020411,19.516394,4.398444,20.099656,0.414897,1.002196,0.518748,0.371033,0.356646,1.460047,0.364134,6.925592e+05
std,21.060168,0.903619,2.549141,3.333666,33.767929,1.353998,1.769053,2.857387,23.513874,0.472782,0.913721,0.506783,0.452338,0.475884,1.102847,0.469334,3.443890e+05
min,25.000000,1.000000,1.000000,1.000000,1850.000000,49.979110,14.447127,0.020000,0.000000,0.004000,0.005000,0.001000,0.004000,0.001000,0.006000,0.003000,1.500000e+05
25%,44.200000,2.000000,2.000000,3.000000,1967.000000,51.109100,18.536220,2.070000,7.000000,0.175000,0.367000,0.237000,0.158000,0.118500,0.592000,0.145000,4.588000e+05
50%,54.400000,3.000000,3.000000,4.000000,1990.000000,52.193604,19.908944,4.010000,13.000000,0.288000,0.700000,0.387000,0.264000,0.235000,1.140000,0.239000,6.200000e+05
75%,68.200000,3.000000,4.000000,6.000000,2014.000000,52.412561,20.992010,6.180000,23.000000,0.466500,1.286000,0.621000,0.415000,0.417000,2.107000,0.405000,8.300000e+05
max,150.000000,6.000000,29.000000,29.000000,2023.000000,54.583210,23.207128,16.940000,208.000000,4.818000,4.996000,4.967000,4.960000,4.985000,4.998000,4.992000,2.500000e+06

In [8]:
df['price_per_m2'] = df['price']/df['squareMeters']
df['price_per_m2'] = df['price_per_m2'].round(2)
df

,id,city,type,squareMeters,rooms,floor,floorCount,buildYear,latitude,longitude,...,ownership,buildingMaterial,condition,hasParkingSpace,hasBalcony,hasElevator,hasSecurity,hasStorageRoom,price,price_per_m2
0,f8524536d4b09a0c8ccc0197ec9d7bde,szczecin,blockOfFlats,63.00,3.0,4.0,10.0,1980.0,53.378933,14.625296,...,condominium,concreteSlab,NaN,yes,yes,yes,no,yes,415000,6587.30
1,accbe77d4b360fea9735f138a50608dd,szczecin,blockOfFlats,36.00,2.0,8.0,10.0,NaN,53.442692,14.559690,...,cooperative,concreteSlab,NaN,no,yes,yes,no,yes,395995,10999.86
2,8373aa373dbc3fe7ca3b7434166b8766,szczecin,tenement,73.02,3.0,2.0,3.0,NaN,53.452222,14.553333,...,condominium,brick,NaN,no,no,no,no,no,565000,7737.61
3,0a68cd14c44ec5140143ece75d739535,szczecin,tenement,87.60,3.0,2.0,3.0,NaN,53.435100,14.532900,...,condominium,brick,NaN,yes,yes,no,no,yes,640000,7305.94
4,f66320e153c2441edc0fe293b54c8aeb,szczecin,blockOfFlats,66.00,3.0,1.0,3.0,NaN,53.410278,14.503611,...,condominium,NaN,NaN,no,no,no,no,no,759000,11500.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18900,ae88d7ea0a7a5fa0e9d287cfd78e5676,bydgoszcz,blockOfFlats,84.00,3.0,NaN,4.0,2000.0,53.112927,17.975630,...,cooperative,brick,NaN,yes,yes,no,no,yes,789000,9392.86
18901,6a4b30b5fcdee00bfe5bcc0da82df9b1,bydgoszcz,blockOfFlats,94.30,4.0,NaN,2.0,1998.0,53.115921,17.956396,...,condominium,NaN,NaN,no,yes,no,no,yes,699000,7412.51
18902,1e7f4f1fdfea31eb84e071d697839632,bydgoszcz,NaN,50.12,2.0,1.0,1.0,NaN,53.126000,18.007900,...,condominium,brick,NaN,yes,no,no,no,no,360000,7182.76
18903,d971c4ed3aab9919bf203e96019a678e,bydgoszcz,tenement,100.00,4.0,3.0,4.0,1910.0,53.126000,18.007900,...,condominium,brick,premium,yes,yes,no,no,yes,590000,5900.00
18904,cd0241b70b79aaaf767a0dd3a7cfbb31,bydgoszcz,NaN,81.07,5.0,1.0,4.0,2019.0,53.115921,17.956396,...,condominium,NaN,NaN,no,yes,yes,no,no,699000,8622.18

In [9]:
mediana = df.groupby('city')['price_per_m2'].median()
mediana = mediana.sort_values(ascending=False)
mediana

city
warszawa       14713.130
krakow         13001.320
gdansk         12098.580
wroclaw        11209.015
gdynia         10583.410
poznan          9791.670
rzeszow         9226.705
lublin          8491.300
bialystok       8150.580
szczecin        7989.845
lodz            7450.110
katowice        7326.055
bydgoszcz       7306.930
radom           6140.225
czestochowa     5948.550
Name: price_per_m2, dtype: float64

In [10]:
import os

lista = []
for i in os.listdir('../data/raw'):
    if 'apartments_pl' in i:
        lista.append(i)

dfs =[]
for x in lista:
    arq = pd.read_csv('../data/raw/'+x)
    index1 = x.index('l')+2
    index2 = x.index('.')
    month = x[index1 : index2]
    arq['month'] = month
    dfs.append(arq)
ap = pd.concat(dfs)

In [11]:
ap.shape

(195568, 29)

In [12]:
ap['month'].value_counts()

month
2024_06    21501
2024_05    20231
2024_04    19259
2023_08    18905
2024_03    17318
2023_09    16997
2023_10    16690
2023_12    16483
2024_02    16361
2023_11    16302
2024_01    15521
Name: count, dtype: int64

In [13]:
ap_sorted_month = ap.sort_values(by='month')
ap_nd = ap_sorted_month.drop_duplicates(subset='id',keep='last')

ap_nd.shape

(92967, 29)

In [14]:
ap_nd = ap_nd.drop(columns='condition')
ap_nd.shape

(92967, 28)

In [15]:
ap_nd['rooms'].isnull().sum().dtype

dtype('int64')

In [16]:
ap_nd['floor'].isnull().sum()

np.int64(15972)

In [17]:
ap_nd['rooms'] = ap_nd['rooms'].astype('Int64')

In [18]:
ap_nd['floor'] = ap_nd['floor'].astype('Int64')

In [19]:
ap_nd[['rooms','floor']].dtypes

rooms    Int64
floor    Int64
dtype: object

In [20]:
ap_nd['price_per_m2'] = ap_nd['price'] / ap_nd['squareMeters']
ap_nd['price_per_m2'] = ap_nd['price_per_m2'].round(2)
ap_nd['price_per_m2']

0         6587.30
12605    19041.10
12604    15675.68
12608    21428.57
12599    14000.00
           ...
7163     11227.67
7162     12631.33
7161     12288.46
7159     20241.10
21500     5076.14
Name: price_per_m2, Length: 92967, dtype: float64

In [21]:
ap_nd['price_per_m2'].describe()

count    92967.000000
mean     13757.449365
std       4913.737980
min       3000.000000
25%      10000.000000
50%      13293.650000
75%      16882.780000
max      32096.770000
Name: price_per_m2, dtype: float64

In [22]:
ap_nd['city_median_m2'] = ap_nd.groupby('city')['price_per_m2'].transform('median')

ap_nd

,id,city,type,squareMeters,rooms,floor,floorCount,buildYear,latitude,longitude,...,buildingMaterial,hasParkingSpace,hasBalcony,hasElevator,hasSecurity,hasStorageRoom,price,month,price_per_m2,city_median_m2
0,f8524536d4b09a0c8ccc0197ec9d7bde,szczecin,blockOfFlats,63.00,3,4,10.0,1980.0,53.378933,14.625296,...,concreteSlab,yes,yes,yes,no,yes,415000,2023_08,6587.30,8862.430
12605,3b0f3451de86ededef13cb439475503d,warszawa,NaN,73.00,3,3,5.0,1953.0,52.223871,21.015783,...,brick,no,no,yes,no,yes,1390000,2023_08,19041.10,16765.790
12604,faabccf5704ba1a95707c8b58b5ac424,warszawa,apartmentBuilding,74.00,3,4,4.0,2021.0,52.166099,21.083576,...,brick,no,yes,yes,no,no,1160000,2023_08,15675.68,16765.790
12608,981edb2353a99e810edd847e40a34194,warszawa,tenement,112.00,5,5,6.0,1912.0,52.221200,21.010700,...,brick,yes,yes,yes,yes,no,2400000,2023_08,21428.57,16765.790
12599,e14b78c0d5361252f087bf92f558ece6,warszawa,blockOfFlats,55.00,2,5,6.0,2001.0,52.140040,21.041640,...,NaN,no,yes,yes,no,no,770000,2023_08,14000.00,16765.790
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7163,bd533fafed2fcc1e1db6feefa7fe6e7a,gdansk,NaN,77.12,4,1,4.0,2024.0,54.341330,18.570670,...,NaN,no,no,NaN,no,no,865878,2024_06,11227.67,13229.625
7162,35bbcb3e58cd0e2884d85f22cd63352d,gdansk,NaN,72.10,3,3,4.0,2024.0,54.341330,18.570670,...,NaN,no,no,NaN,no,no,910719,2024_06,12631.33,13229.625
7161,41df673f01ce915197dd61351a6d3a6c,gdansk,NaN,52.00,3,3,3.0,NaN,54.343800,18.527700,...,NaN,yes,no,yes,no,no,639000,2024_06,12288.46,13229.625
7159,3c3b13fd2e7df43ae6b6383a4f203e05,gdansk,NaN,80.34,3,<NA>,3.0,2023.0,54.399490,18.569620,...,NaN,no,no,no,no,no,1626170,2024_06,20241.10,13229.625
21500,60fcbfa2a2a48ebcc2e554efba7f2729,bydgoszcz,tenement,59.10,2,1,1.0,1910.0,53.126792,18.005991,...,brick,yes,no,no,no,yes,300000,2024_06,5076.14,7583.770

In [23]:
ap_nd['ratio'] = ap_nd['price_per_m2'] / ap_nd['city_median_m2']
ap_nd['ratio'].describe()

count    92967.000000
mean         1.037128
std          0.251720
min          0.379111
25%          0.862969
50%          1.000000
75%          1.170112
max          2.747322
Name: ratio, dtype: float64

In [24]:
import numpy as np

ap_nd['is_outlier'] = np.where((ap_nd['ratio'] < 0.5) | (ap_nd['ratio'] > 2.0) , True, False)

ap_nd['is_outlier'].sum()

np.int64(426)

In [25]:
ap_nd[ap_nd['is_outlier']]['city'].value_counts()

city
gdynia       137
gdansk        96
warszawa      70
krakow        57
katowice      23
wroclaw       16
bydgoszcz     12
poznan         8
szczecin       7
Name: count, dtype: int64

In [26]:
x = ap_nd.groupby('city')['is_outlier'].mean().sort_values(ascending=False)
x

city
gdynia         0.038386
gdansk         0.011645
katowice       0.009595
krakow         0.004018
bydgoszcz      0.003309
szczecin       0.002815
poznan         0.002198
warszawa       0.002189
wroclaw        0.001667
bialystok      0.000000
czestochowa    0.000000
radom          0.000000
lublin         0.000000
lodz           0.000000
rzeszow        0.000000
Name: is_outlier, dtype: float64

In [27]:
ap_nd.to_csv('../data/clean/apartments_clean.csv', index=False)

In [28]:
ap_nd.shape

(92967, 32)

In [29]:
removed_cols = set(ap.columns) - set(ap_nd.columns)
int_cols = list(ap_nd.columns[ap_nd.dtypes == 'Int64'])
n_out = ap_nd['is_outlier'].sum()

print('=== DATA QUALITY REPORT ===')
print(f'Rows in raw data:      {len(ap):,}')
print(f'Duplicates removed:    {len(ap) - len(ap_nd):,}')
print(f'Rows in clean data:    {len(ap_nd):,}')
print(f'Columns removed:       {sorted(removed_cols)}')
print(f'Converted to Int64:    {int_cols}')
print(f'Outliers flagged:      {n_out:,} ({n_out / len(ap_nd):.2%})')

=== DATA QUALITY REPORT ===
Rows in raw data:      195,568
Duplicates removed:    102,601
Rows in clean data:    92,967
Columns removed:       ['condition']
Converted to Int64:    ['rooms', 'floor']
Outliers flagged:      426 (0.46%)